# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            kdbanman
description:      'A software developer keen on making things better.'
url:              http://kdbanman.com
baseurl:          /

author:
  name:           'Kirby Banman'
  url:            https://github.com/kdbanman

paginate:         1
paginate_path:    /projects/page:num
